sudo: required
services: 
  - docker
before_install:
  - docker build -t msevugan/docker-react -f Dockerfile.dev  .
script:
  - docker run msevugan/docker-react npm run test -- --coverage #default npm run test hangs after execution. coverage option exists back to command line 

